# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 23:20
from __future__ import unicode_literals

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowRoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inc_Name', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('Business_address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('showrooms', models.ManyToManyField(blank=True, related_name='_inc_showrooms_+', to='ShowRoom.Inc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='incprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='IncProfile',
        ),
    ]
