# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoom', '0004_auto_20161129_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc',
            name='showroom',
            field=models.ManyToManyField(blank=True, related_name='_inc_showroom_+', to='ShowRoom.Inc'),
        ),
    ]
