# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0007_auto_20161128_0341'),
        ('ShowRoom', '0008_auto_20161129_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='PO',
            fields=[
                ('PO_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disenador.Delivery')),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='url',
        ),
        migrations.AddField(
            model_name='store',
            name='web_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.Store'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='Store_Name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='po',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.Store'),
        ),
    ]
