# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoom', '0009_auto_20161130_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Sate',
            new_name='State',
        ),
    ]
