# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0007_auto_20161128_0341'),
        ('ShowRoom', '0010_auto_20161202_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disenador.Item')),
                ('item_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disenador.Item_Available_Sizes')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowRoom.PO')),
            ],
        ),
        migrations.AddField(
            model_name='po',
            name='items',
            field=models.ManyToManyField(through='ShowRoom.Item_chart', to='Disenador.Item_Available_Sizes'),
        ),
    ]
