# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0014_size_group_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShowRoom', '0012_auto_20161210_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='delivery',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='po',
            name='designer',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='po_entry',
            name='baseItem',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Item_Available_Sizes'),
            preserve_default=False,
        ),
    ]
