# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0019_size_order'),
        ('ShowRoom', '0017_auto_20161230_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Billing_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='po_entry',
            name='item',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='po_entry',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='Sample_shipping_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='po',
            name='total_value',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
