# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 04:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disenador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('shipping_date', models.DateField()),
                ('cancel_date', models.DateField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disenador.Collection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disenador.Item')),
            ],
        ),
    ]
