# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0002_collection_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='item',
        ),
        migrations.AddField(
            model_name='delivery',
            name='item',
            field=models.ManyToManyField(to='Disenador.Item'),
        ),
    ]
