# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disenador', '0003_auto_20161123_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('materialPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('designer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Extra_Attribute'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item',
            field=models.ManyToManyField(blank=True, to='Disenador.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_or_print',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Color'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disenador.SizeChart'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Material'),
        ),
    ]
