# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0005_auto_20161123_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='lookbook',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item_available_sizes',
            name='qty_canceled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_available_sizes',
            name='qty_shipped',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_available_sizes',
            name='qty_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
