# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0006_auto_20161123_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='colorPrice',
            new_name='color_price',
        ),
    ]
