# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disenador', '0007_auto_20161128_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='designer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
