# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disenador', '0008_delivery_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('sizePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('designer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10)),
                ('designer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sizechart',
            name='designer',
        ),
        migrations.AddField(
            model_name='extra_attribute',
            name='name',
            field=models.CharField(default=999, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SizeChart',
        ),
        migrations.AddField(
            model_name='size',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Size_Group'),
        ),
    ]
