# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0010_auto_20161208_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Disenador.Size_Group'),
        ),
    ]
