# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0011_item_size_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_available_sizes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disenador.Size'),
        ),
    ]
