# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disenador', '0012_auto_20161210_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='BasePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='baseitem',
            unique_together=set([('clave', 'designer')]),
        ),
    ]
