# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0013_auto_20161211_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='size_group',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
