# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disenador', '0014_size_group_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('base', 'color_or_print', 'material', 'attribute', 'size_group')]),
        ),
    ]
