# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Disenador', '0017_auto_20161222_2132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseitem',
            unique_together=set([('clave', 'name', 'designer')]),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together=set([('color_or_print', 'designer')]),
        ),
        migrations.AlterUniqueTogether(
            name='item_available_sizes',
            unique_together=set([('item', 'size')]),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set([('name', 'designer')]),
        ),
        migrations.AlterUniqueTogether(
            name='size_group',
            unique_together=set([('group_name', 'designer')]),
        ),
    ]
